name: Bank Management System CI

on:
  push:
    branches: [ main ]   # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]   # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2   # Checkout the repository code

      - name: Set up CMake
        run: |
          mkdir build
          cd build
          cmake ..  # Configure CMake for the project

      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release  # Build the project

      - name: Run Tests
        run: |
          cd build
          ctest -C Release  # Run tests configured with CTest
